[package]
name = "pluralsnug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hocon = "0.9.0"
serde = { version = "1.0.188", features = ["derive"] }
